name: Build Nukkit2B2HEdition

on:
  push:
    branches:
      - master # o la rama que uses

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Build Nukkit
        run: ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Nukkit2B2HEdition
          path: build/libs/*.jar
